### ISSUE TITLE
[Issue] QC.sh with precompiled binary

### ISSUE THREAD

**Issue by r-mashoodh** [huishenlab/biscuit#13]
Apologies if I've missed this somewhere in the docs but I am trying to run `QC.sh` on my data. I've created the QC assets with the perl script. 

However `QC.sh` *I think* is struggling to find biscuit -- and not sure how I can specify this?

I've run biscuit commands by calling `../software/biscuit_0_3_16_linux_amd64`

here's what I get when trying to run QC.sh:
```
perl ../software/QC.sh QC_assets ../genomes/n_vesp/GCF_001412225.1_Nicve_v1.0_genomic.fa FCNC_01 FCNC_01_output.bam 

## Running BISCUIT QC script with following configuration ##
==============
Sample Name        : FCNC_01
Input BAM          : FCNC_01_output.bam
Input VCF          : <unused>
Output Directory   : BISCUITqc
Assets Directory   : QC_assets
Reference          : ../genomes/n_vesp/GCF_001412225.1_Nicve_v1.0_genomic.fa
Keep *.tmp.* files : false
CPGS               : QC_assets/cpg.bed.gz
TOPGC              : QC_assets/windows100bp.gc_content.top10p.bed.gz
BOTGC              : QC_assets/windows100bp.gc_content.bot10p.bed.gz
==============
Using biscuit found at: 
Using samtools found at: /usr/bin/samtools
Using bedtools found at: /usr/bin/bedtools
Using awk found at: /usr/bin/awk
Starting BISCUIT QC at Mon  2 Aug 10:35:14 BST 2021

Unknown option: tee
Usage:

parallel [options] [command [arguments]] < list_of_arguments
parallel [options] [command [arguments]] (::: arguments|:::: argfile(s))...
cat ... | parallel --pipe [options] [command [arguments]]

-j n            Run n jobs in parallel
-k              Keep same order
-X              Multiple arguments with context replace
--colsep regexp Split input on regexp for positional replacements
{} {.} {/} {/.} {#} {%} {= perl code =} Replacement strings
{3} {3.} {3/} {3/.} {=3 perl code =}    Positional replacement strings
With --plus:    {} = {+/}/{/} = {.}.{+.} = {+/}/{/.}.{+.} = {..}.{+..} =
                {+/}/{/..}.{+..} = {...}.{+...} = {+/}/{/...}.{+...}

-S sshlogin     Example: foo@server.example.com
--slf ..        Use ~/.parallel/sshloginfile as the list of sshlogins
--trc {}.bar    Shorthand for --transfer --return {}.bar --cleanup
--onall         Run the given command with argument on all sshlogins
--nonall        Run the given command with no arguments on all sshlogins

--pipe          Split stdin (standard input) to multiple jobs.
--recend str    Record end separator for --pipe.
--recstart str  Record start separator for --pipe.

See 'man parallel' for details

Academic tradition requires you to cite works you base your article on.
When using programs that use GNU Parallel to process data for publication
please cite:

  O. Tange (2011): GNU Parallel - The Command-Line Power Tool,
  ;login: The USENIX Magazine, February 2011:42-47.

This helps funding further development; AND IT WON'T COST YOU A CENT.
If you pay 10000 EUR you should feel free to use GNU Parallel without citing.
```

I'd appreciate any advice ...

**Comment by jamorrison** [comment]
Hi @r-mashoodh,

In order for the QC script to find BISCUIT, it needs to be included in your PATH environment variable. In case you haven't worked with the PATH variable before, you can add

`export PATH="/path/to/directory/with/biscuit/executable:${PATH}"`,

to your `.bashrc` file (this will be slightly different for other shells).

On a related note, the QC script can be run in a couple of different ways:

1. `/path/to/QC.sh [options] assets_directory genome sample_name in_bam`
2. `bash /path/to/QC.sh [options] assets_directory genome sample_name in_bam`

**Comment by r-mashoodh** [comment]
hi, thanks for the response ... I should have been clearer, so I did try placing the executable in the path ... and I still get that error message. 

Does the executable have to be named something in particular? currently it's 'biscuit_0_3_16_linux_amd64'?

thank you!

**Comment by jamorrison** [comment]
That's not a problem! I understand what you're looking for now. The QC script is specifically looking for "biscuit," so you'll want to change the executable name accordingly.

Let me know if that doesn't work.

**Comment by r-mashoodh** [comment]
Thanks again! I think the problem lies in the fact that we're not allowed on our cluster ...

is there a place in the script where I can make the path explicit?

**Comment by jamorrison** [comment]
There are a couple of options.

If the `biscuit_0_3_16_linux_amd64` executable is in your PATH already and you are able to change the name of the file, then you can change the name to biscuit (`mv biscuit_0_3_16_linux_amd64 biscuit` should do it). This will line the name of the executable up with what the QC script is expecting.

If the `biscuit_0_3_16_linux_amd64` executable is not in your PATH or you can't change its name, you can try changing each instance of `biscuit` to `/absolute/path/to/biscuit_0_3_16_linux_amd64` in the QC script using your preferred editor. This will change what the QC script is using when calling biscuit. (You'll probably also want to comment out the portion of `check_path` that looks for the biscuit executable in your PATH - should be approximately lines 42-47.)

**Comment by r-mashoodh** [comment]
hi! me again ...

I went in an edited the QC.sh script. But i get the same error and I've just realised that it's an issue that is coming up before the script calls biscuit. 

Line 111
`samtools view -hb ${in_bam} | parallel -j7 -k --tmpdir ${outdir} --pipe --tee {} ::: \`

which makes complete sense because the error message is about parallel ... doh. 

The error above says unknown option
`Unknown option: tee`

```
parallel --version
GNU parallel 20161222
```

So the biscuit path would have been a problem eventually, however what's your advice re: parallel?

**Comment by jamorrison** [comment]
What command are you using to run `QC.sh`?

**Comment by jamorrison** [comment]
Also, you might want to try updating the version of GNU parallel you are using. The QC script is known to work with GNU parallel 20201122.

**Comment by r-mashoodh** [comment]
i'm using 
bash QC.sh 
same issue if I make QC.sh executable. I think it *must* be down to the parallel version ...

I'll have to ask the facility if they are willing to update it (chances are no, because it might break existing things). 

What does the output of the QC look like?

**Comment by jamorrison** [comment]
That does indeed seem like it's a `parallel` issue then...

The output from `QC.sh` is a set of text files that can be used in conjunction with MultiQC to quickly generate a report containing the various QC metrics measured by biscuit.

Generally, I use the QC to verify the samples I'm processing seem reasonable (i.e., good alignment rates, reasonable duplicate rate, proper cytosine retention levels, etc.). That said, it isn't necessary to run `QC.sh` for any downstream analyses.

As a side note, the next release of BISCUIT will include an easy way to avoid using `parallel`, but that's still in the works at the moment.
