### ISSUE TITLE
Issues with the QC script

### ISSUE THREAD

**Issue by SSunkara** [huishenlab/biscuit#14]
Hello,

There is a call to a 'biscuit qc' command in your QC.sh, which breaks. Is this a new version of biscuit that has the qc command? 

Is your latest release ready for prime-time, or is it still experimental?

Thanks,
Sirisha

**Comment by jamorrison** [comment]
Hi @SSunkara,

The `QC.sh` script that calls `biscuit qc` is for the current HEAD version of BISCUIT, which will eventually become the next release. So, at this time, it is still experimental.

The QC script corresponding to BISCUIT v0.3.16 (the latest release) can be found on the [release page](https://github.com/huishenlab/biscuit/releases/tag/v0.3.16.20200420).

If you want to use the `QC.sh` script with `biscuit qc` in it, you will have to [clone the repo](https://huishenlab.github.io/biscuit/#download-source-code-and-compile). But, as I mentioned, this is still in an experimental state.
