### ISSUE TITLE
Conversion Rate calculation

### ISSUE THREAD

**Issue by Irfanwustl** [huishenlab/biscuit#15]
Hi,
Thanks for the great tool.

I have used BISCUIT and generated bw and bam files. However, I am trying to calculate the bisulfite conversion rate. Is there any way so that BISCUIT can provide the rate from the aligned bam file?

Or do I need to write a script? In the aligned bam file, I have found that there are ZC (Number of cytosine conversions) and ZR (Number of cytosine retentions) tags. Probably I need to use those to calculate the rate?

**Comment by jamorrison** [comment]
Hi @Irfanwustl,

Bisulfite conversion can be probed in a couple different ways. To look at conversion/retention in a quality control manner, you can run the `QC.sh` script provided on the [release page](https://github.com/huishenlab/biscuit/releases/tag/v0.3.16.20200420), which creates files that can be read by MultiQC. The Retention vs. Base Position in Read and Cytosine Retention reports would be the ones that are most relevant in your case.

If you are planning to use methylation beta values in your downstream analysis, I would suggest following the documentation to generate a [pileup VCF](https://huishenlab.github.io/biscuit/docs/pileup.html) and [CpG BED](https://huishenlab.github.io/biscuit/docs/methylextraction.html). You can then use the beta values to determine conversion/retention.

**Comment by Irfanwustl** [comment]
Many thanks
