### ISSUE TITLE
Allow gzipped input for SNP BED

### ISSUE THREAD

**Issue by njspix** [huishenlab/biscuit#17]
It appears that the `biscuit epiread` command is unable to accept gzipped BED input for the -B parameter. It would be nice for this to accept either gzipped or uncompressed BED files.

**BISCUIT version**
Version: 1.0.2.20220113

Thanks!

**Comment by jamorrison** [comment]
This has been addressed in commit 291729e4d3d460cfa1bda1b655ff91eda5ae9bdf. It will be available in the next release.
