### ISSUE TITLE
[Issue] Biscuit align failed

### ISSUE THREAD

**Issue by brainfo** [huishenlab/biscuit#18]
**Describe the bug**
Biscuit align failed with the log:
```
[M::bwa_idx_load_from_disk] read 0 ALT contigs
[M::process] read 2314482 sequences (320000078 bp)...
[M::process] read 2315378 sequences (320000005 bp)...
[M::mem_pestat] # candidate unique pairs: 173219
[M::mem_pestat] (25, 50, 75) percentile: (335, 395, 446)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (113, 668)
[M::mem_pestat] mean and std.dev: (384.67, 92.66)
[M::mem_pestat] low and high boundaries for proper pairs: (2, 779)
[M::mem_process_seqs] Processed 2314482 reads in 3612.258 CPU sec, 113.153 real sec
[fputs] Broken pipe
```

**BISCUIT version**
Version: 1.0.2.20220113

**Minimally Reproducible Example**
1. Reference genome: GRCm39+lambda (Given by my coworker so I actually don't know this source for this time). But I buid index by biscuit index and samtools faix
2. biscuit align -@ {threads} -b 1 \
                    {reference} {r1} {r2} 2> {log}/{name}_biscuit.log | \
                samblaster --addMateTags 2> {log}/{name}_samblaster.log | \
                samtools sort -@ {threads} -m 50G -o {bam} -O BAM - 2> {log}/{name}_sort.log

`biscuit align -@ 32 -b 1                     /mnt/data/hong/share_to_hong/0_ref/GRCm39_lambda.fa /mnt/data/hong/2022/mouse_placenta/WGBS/output/analysis/trim_glare/R10_5DHT11/R10_5DHT11_1_val_1.fq.gz /mnt/data/hong/2022/mouse_placenta/WGBS/output/analysis/trim_glare/R10_5DHT11/R10_5DHT11_2_val_2.fq.gz 2> //mnt/data/hong/2022/mouse_placenta/WGBS/logs/biscuit/R10_5DHT11/R10_5DHT11_biscuit.log |                 samblaster --addMateTags 2> //mnt/data/hong/2022/mouse_placenta/WGBS/logs/biscuit/R10_5DHT11/R10_5DHT11_samblaster.log |                 samtools sort -@ 32 -m 50G -o //mnt/data/hong/2022/mouse_placenta/WGBS/output/analysis/biscuit/R10_5DHT11/R10_5DHT11.bam -O BAM - 2> //mnt/data/hong/2022/mouse_placenta/WGBS/logs/biscuit/R10_5DHT11/R10_5DHT11_sort.log`

**Expected behavior**
Is this because of something wrong with the reference index?
Also, I didn't give -R (read group information). is -R a mandatory parameter?

**Comment by jamorrison** [comment]
Hi @brainfo,

The `[fputs] Broken pipe` error is coming from a downstream error (either from samblaster or samtools), which causes biscuit to produce a broken pipe error. I would suggest making sure that all variables are defined (threads, reference, r1, r2, etc.) prior to calling your one-liner.

As far as the reference and read group flag, biscuit can handle joint genomes (like what you are using). For read groups, the `-R` flag is optional, so that won't cause your issue either.

**Comment by TrueScience** [comment]
**Describe the bug**
Segmentation fault when using biscuit align with -p option for interleaved input fastq file


$ biscuit align -MC -k 12 -t 6  -p hg19.fa BST_50_1_CRC_S4_R1_R2.fastq > BST_50_1_CRC_S4.bam
[M::bwa_idx_load_from_disk] read 0 ALT contigs
[M::process] read 428404 sequences (60000236 bp)...
[bseq_classify] 0 SE sequences; 428404 PE sequences
[M::process] read 428114 sequences (60000124 bp)...
[M::mem_pestat] # candidate unique pairs: 98565
[M::mem_pestat] (25, 50, 75) percentile: (291, 307, 318)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (237, 372)
[M::mem_pestat] mean and std.dev: (304.11, 22.07)
[M::mem_pestat] low and high boundaries for proper pairs: (210, 399)
[M::mem_process_seqs] Processed 428404 reads in 965.734 CPU sec, 161.535 real sec
[bseq_classify] 0 SE sequences; 428114 PE sequences
[M::process] read 428398 sequences (60000072 bp)...
[M::mem_pestat] # candidate unique pairs: 98816
[M::mem_pestat] (25, 50, 75) percentile: (291, 307, 318)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (237, 372)
[M::mem_pestat] mean and std.dev: (304.06, 21.88)
[M::mem_pestat] low and high boundaries for proper pairs: (210, 399)
[M::mem_process_seqs] Processed 428114 reads in 995.806 CPU sec, 166.452 real sec
[bseq_classify] 0 SE sequences; 428398 PE sequences
[M::process] read 428288 sequences (60000164 bp)...
[M::mem_pestat] # candidate unique pairs: 98667
[M::mem_pestat] (25, 50, 75) percentile: (291, 307, 318)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (237, 372)
[M::mem_pestat] mean and std.dev: (304.07, 21.94)
[M::mem_pestat] low and high boundaries for proper pairs: (210, 399)
[M::mem_process_seqs] Processed 428398 reads in 1043.869 CPU sec, 174.309 real sec
Segmentation fault

**BISCUIT version**
Program: BISCUIT (BISulfite-seq CUI Toolkit)
Version: 0.3.8.20180515
