### ISSUE TITLE
[Issue] Alignment Issue

### ISSUE THREAD

**Issue by JunxiFeng** [huishenlab/biscuit#20]
Hello,

So I used biscuit to index successfully, but when I moved on to alignment I kept running into the issue shown below. 

**Screenshots**
Attached is part of the alignment output I got, which gives some strange outputs. 
![截屏2022-05-07 上午9 35 41](https://user-images.githubusercontent.com/60299660/167263518-178baf62-a990-4be8-9342-ab2530e7650b.png)

The command I used is, which I don't see any problem
![截屏2022-05-07 上午9 38 45](https://user-images.githubusercontent.com/60299660/167263630-321f74cb-63c2-4c1a-85e8-78084d254085.png)

Do you have any idea what the problem might be? Thanks a lot!!

**Comment by jamorrison** [comment]
Hi @JunxiFeng,

When running BISCUIT, the `-1` and `-2` flags are for specifying single reads from the command line. With paired end FASTQs, you don't have to include those flags:

`biscuit align -R (read group) read1.fastq read2.fastq`

I hope this helps.
Jacob

**Comment by JunxiFeng** [comment]
Thanks a lot! !

Just another quick question, does biscuit have the option to output the uniquely mapped reads? If so, how are they counted? (like how are read defined as uniquely mapped, since different tools define uniqueness differently)

Again, thank you so much!

**Comment by jamorrison** [comment]
biscuit itself does not have a command for removing duplicate reads. However, we suggest using the [biscuitBlaster pipeline](https://huishenlab.github.io/biscuit/biscuitblaster/#version-1) to mark duplicates and coordinate sort BAMs. This pipeline uses [samblaster](https://github.com/GregoryFaust/samblaster) to mark duplicates (you can also remove them instead of retaining them) and samtools to do the sorting.

**Comment by JunxiFeng** [comment]
Hi, 

I think uniquely mapped read is not the same as duplicate reads, could you confirm this? Thanks!

**Comment by JunxiFeng** [comment]
Hello again, 

Will the publication will be coming up soon? I would appreciate it if I can get a more detailed insight of the tool! Thanks!

**Comment by jamorrison** [comment]
Sorry, I got my terms mixed up. BISCUIT treats uniquely mapped reads like `bwa mem`. A basic way to filter for uniquely mapped reads would be to run the aligned reads through `samtools view -q 40`. If you need a more thorough filtering, this [Bioinformatics StackExchange post](https://bioinformatics.stackexchange.com/questions/508/obtaining-uniquely-mapped-reads-from-bwa-mem-alignment) might be a place to start.

As far as a publication, there are some things we're still working on, so not sure on when that will be available. In the mean time, there is a documentation website (https://huishenlab.github.io/biscuit/) that might help with some more details on BISCUIT.

**Comment by JunxiFeng** [comment]
Thanks so much for the answer! 

I also have another question regarding the alignment output:

![image](https://user-images.githubusercontent.com/60299660/169218253-6c2402e0-6c20-4a29-b434-59a7ad8cca1f.png)


As shown in the image, since both the primary and alternative hit all shows CIGAR of 96M:
    1. why is this MAPQ 60 when it looks like a multiple mapping?
    2. why would the AS > XS in this case?

Thank you so much!!

**Comment by zwdzwd** [comment]
Hi @JunxiFeng I think the MAPQ is 60 because the alternative mapping contains mismatches despite 96M in CIGAR. This is consistent with  XS = 90 and AS = 96. The optimal mapping has no mismatches. Hope this clarifies.
