### ISSUE TITLE
[Issue] trivial code correction for pileup.c

### ISSUE THREAD

**Issue by vpbrendel** [huishenlab/biscuit#22]
pileup.c SHOULD BE c CURRENT
126c126
<       fprintf(out, "\t%"PRId64"\t%1.3f%%", k_hch,  b_hch  / (double) k_hch  * 100);
---
>       fprintf(out, "\t%"PRId64"\t%1.3f%%", k_hchh, b_hch  / (double) k_hch  * 100);

147c147
<       fprintf(out, "\t%"PRId64"\t%1.3f%%", k_ch,  b_ch  / (double) k_ch  * 100);
---
>       fprintf(out, "\t%"PRId64"\t%1.3f%%", k_chh, b_ch  / (double) k_ch  * 100);

**Comment by zwdzwd** [comment]
Thank you for reporting! This is my oversight. We will fix.

**Comment by jamorrison** [comment]
Thanks @vpbrendel for pointing out these fixes. They have now been fixed and will be in the next release of BISCUIT.
