### ISSUE TITLE
Mismatch between `vcf2bed` and `epiread`

### ISSUE THREAD

**Issue by ekushele** [huishenlab/biscuit#23]
Please fill in as much as possible. The more information provided, the more likely we are to be able to help.

**Describe the bug**
The bedGraph from biscuit vcf2bed is not compatible with the coverage in the epiread file.
The epiread file shows a coverage of 14 and a methylation level of 0.5, while the bedGraph from the vcf shows coverage of 5 and methylation of 0.4.
When looking at the VCF file directly, it shows in the SP flag: C7T3Y4, indicating a coverage of 14. This site has C->T SNP, which might be affecting the calculation in the bedGraph generated from the VCF file.

Command to create bedGraph:
`biscuit vcf2bed -k1 methylation_extract/small.hg19.vcf.gz`
The line in the bedGraph file:
```
chr1	205640815	205640816	0.4	5	
```

Command to create VCF: 
`biscuit pileup  hg19.fa biscuit_alignment/small.sorted.bam  -o methylation_extract/small.hg19.vcf`
`bgzip -f methylation_extract/small.hg19.vcf`
`tabix -f -p vcf methylation_extract/small.hg10.vcf.gz`

The lines in the VCF file:
```
chr1	205640815	.	C	.	42	PASS	NS=1;CX=CHG;N5=CCCCG	GT:GL1:GQ:DP:SP:CV:BT	0/0:-1,-11,-67:42:14:C5Y9:9:0.000
chr1	205640816	.	C	T	35	PASS	NS=1;CX=CG;N5=CCCGT	GT:GL1:GQ:DP:SP:AC:AF1	0/1:-11,-3,-30:35:15:C7T3Y4:10:0.30
chr1	205640817	.	G	.	42	PASS	NS=1;CX=CG;N5=GACGG	GT:GL1:GQ:DP:SP:CV:BT	0/0:-1,-11,-67:42:15:G11R3:5:0.400
```
Command to create epiread file:
`biscuit epiread -O -B snp.bed | sort --parallel=1 -T . -k2,2 -k1,1 -k4,4 -k3,3n > small.original.epiread`
`sort -k1,1Vf -k5,5n --parallel=$threads -T . small.original.epiread | bgzip > small.original.epiread.gz`
`tabix -0 -s 1 -b 5 -e 5 small.original.epiread.gz`

snp.bed file contains:
```
chr1	205640903	205640904	G	A	0/1	29	G2A2R3	4	0.5	rs6685508	1	0.497953	G	A
```

The command to extract the coverage in the position `205640815` for epiread file:
`tabix original.epiread.gz chr1:205640700-205640816`

The epiread in this regions is:

```
chr1	A00221:276:HLFLFDMXX:1:1101:32624:3161	1	-	205640707	CCCC	.	.
chr1	A00221:276:HLFLFDMXX:1:1131:24514:35524	1	-	205640707	CCC	.	.
chr1	A00221:276:HLFLFDMXX:1:2319:20437:31062	1	+	205640707	CCCC	.	.
chr1	A00221:276:HLFLFDMXX:1:2319:20437:31062	2	+	205640707	----	.	.
chr1	A00221:276:HLFLFDMXX:1:2419:23050:33113	1	+	205640707	CCCC	.	.
chr1	A00221:276:HLFLFDMXX:2:1139:32606:9330	1	-	205640707	CCC	.	.
chr1	A00221:276:HLFLFDMXX:2:1304:14778:18443	1	-	205640707	CCCCT	.	.
chr1	A00221:276:HLFLFDMXX:2:2338:5665:6230	1	-	205640707	CC	.	.
chr1	A00221:276:HLFLFDMXX:2:2338:5665:6230	2	-	205640707	--	.	.
chr1	A00221:276:HLFLFDMXX:2:1304:14778:18443	2	-	205640713	----	.	.
chr1	A00221:276:HLFLFDMXX:2:2455:18132:10066	1	+	205640713	CTCC	.	.
chr1	A00221:276:HLFLFDMXX:2:2455:18132:10066	2	+	205640713	----	.	.
chr1	A00221:276:HLFLFDMXX:1:2460:23728:24706	1	-	205640723	-CC	.	.
chr1	A00221:276:HLFLFDMXX:2:2239:22562:3552	1	+	205640723	CCT	.	.
chr1	A00221:276:HLFLFDMXX:2:2239:22562:3552	2	+	205640723	---	.	.
chr1	A00221:276:HLFLFDMXX:1:2238:32289:2174	1	+	205640751	CTC	.	.
chr1	A00221:276:HLFLFDMXX:1:2238:32289:2174	2	+	205640751	--C	.	.
chr1	A00221:276:HLFLFDMXX:1:2419:23050:33113	2	+	205640751	-C	.	.
chr1	A00221:276:HLFLFDMXX:1:2460:23728:24706	2	-	205640751	--	.	.
chr1	A00221:276:HLFLFDMXX:2:2118:5439:7560	1	+	205640751	CCC	.	.
chr1	A00221:276:HLFLFDMXX:2:2118:5439:7560	2	+	205640751	--	.	.
chr1	A00221:276:HLFLFDMXX:1:1157:32443:27336	1	+	205640815	CCCC	205640903	G
chr1	A00221:276:HLFLFDMXX:1:1171:7699:10066	1	-	205640815	TC	.	.
chr1	A00221:276:HLFLFDMXX:1:1171:7699:10066	2	-	205640815	--	.	.
chr1	A00221:276:HLFLFDMXX:1:2170:25427:20729	1	+	205640815	TCC	.	.
chr1	A00221:276:HLFLFDMXX:1:2170:25427:20729	2	+	205640815	---	.	.
chr1	A00221:276:HLFLFDMXX:1:2232:18466:1470	1	-	205640815	C	.	.
chr1	A00221:276:HLFLFDMXX:1:2232:18466:1470	2	-	205640815	-	.	.
chr1	A00221:276:HLFLFDMXX:1:2409:7853:6417	1	+	205640815	CCC	.	.
chr1	A00221:276:HLFLFDMXX:1:2409:7853:6417	2	+	205640815	---	.	.
chr1	A00221:276:HLFLFDMXX:2:1101:9290:33207	1	-	205640815	T-	.	.
chr1	A00221:276:HLFLFDMXX:2:1101:9290:33207	2	-	205640815	--	.	.
chr1	A00221:276:HLFLFDMXX:2:2219:8486:8578	1	+	205640815	TC	.	.
chr1	A00221:276:HLFLFDMXX:2:2219:8486:8578	2	+	205640815	--	.	.
```

The command to run epiread in old format, with -A 
`biscuit epiread -O -A -B snp.bed hg19.fa small.bam > small_withA.epired`

The command :
`less small_withA.epiread | grep 205640815`

```
chr1	A00221:276:HLFLFDMXX:2:1304:14778:18443	1	-	205640707,205640713,205640723,205640751,205640815	CCCCT	.	.
chr1	A00221:276:HLFLFDMXX:2:1304:14778:18443	2	-	205640713,205640723,205640751,205640815	----	.	.
chr1	A00221:276:HLFLFDMXX:2:2455:18132:10066	1	+	205640713,205640723,205640751,205640815	CTCC	.	.
chr1	A00221:276:HLFLFDMXX:2:2455:18132:10066	2	+	205640713,205640723,205640751,205640815	----	.	.
chr1	A00221:276:HLFLFDMXX:2:2239:22562:3552	1	+	205640723,205640751,205640815	CCT	.	.
chr1	A00221:276:HLFLFDMXX:2:2239:22562:3552	2	+	205640723,205640751,205640815	---	.	.
chr1	A00221:276:HLFLFDMXX:1:2460:23728:24706	1	-	205640723,205640751,205640815	-CC	.	.
chr1	A00221:276:HLFLFDMXX:1:2460:23728:24706	2	-	205640751,205640815	--	.	.
chr1	A00221:276:HLFLFDMXX:1:2419:23050:33113	2	+	205640751,205640815	-C	.	.
chr1	A00221:276:HLFLFDMXX:1:2238:32289:2174	1	+	205640751,205640815,205640858	CTC	.	.
chr1	A00221:276:HLFLFDMXX:2:2118:5439:7560	1	+	205640751,205640815,205640858	CCC	.	.
chr1	A00221:276:HLFLFDMXX:1:2238:32289:2174	2	+	205640751,205640815,205640858	--C	.	.
chr1	A00221:276:HLFLFDMXX:2:2118:5439:7560	2	+	205640751,205640815	--	.	.
chr1	A00221:276:HLFLFDMXX:1:2232:18466:1470	1	-	205640815	C	.	.
chr1	A00221:276:HLFLFDMXX:1:2232:18466:1470	2	-	205640815	-	.	.
chr1	A00221:276:HLFLFDMXX:1:1171:7699:10066	1	-	205640815,205640858	TC	.	.
chr1	A00221:276:HLFLFDMXX:1:1171:7699:10066	2	-	205640815,205640858	--	.	.
chr1	A00221:276:HLFLFDMXX:2:2219:8486:8578	1	+	205640815,205640858	TC	.	.
chr1	A00221:276:HLFLFDMXX:2:2219:8486:8578	2	+	205640815,205640858	--	.	.
chr1	A00221:276:HLFLFDMXX:2:1101:9290:33207	1	-	205640815,205640858	T-	.	.
chr1	A00221:276:HLFLFDMXX:2:1101:9290:33207	2	-	205640815,205640858	--	.	.
chr1	A00221:276:HLFLFDMXX:1:1157:32443:27336	1	+	205640815,205640858,205640885,205640917	CCCC	205640903	G
chr1	A00221:276:HLFLFDMXX:1:2170:25427:20729	1	+	205640815,205640858,205640885	TCC	.	.
chr1	A00221:276:HLFLFDMXX:1:2170:25427:20729	2	+	205640815,205640858,205640885	---	.	.
chr1	A00221:276:HLFLFDMXX:1:2409:7853:6417	1	+	205640815,205640858,205640885	CCC	.	.
chr1	A00221:276:HLFLFDMXX:1:2409:7853:6417	2	+	205640815,205640858,205640885	---	.	.

```

**BISCUIT version**
Version: 1.0.3.dev

**Minimally Reproducible Example**
1. Reference genome: hg19
2. Small dataset to run on (make sure the dataset returns the same error)
2. Command(s) run:

**Expected behavior**
The epiread file shows a coverage of 14 and a methylation level of 0.5, while the bedGraph from the vcf shows coverage of 5 and methylation of 0.4. I would like to see concordance between the two

**Computer Resources**
 - OS: Linux x86_64
 - RAM: 8G
 - CPUs: 1

**Additional context**

**Screenshots**
The region of the position (chr1:205640809-205640819), colored by bisulfite mode, with View as pairs mode
 <img width="1435" alt="image" src="https://user-images.githubusercontent.com/56130301/173298663-0f11981e-6461-49e9-8f5a-470db7e9d7ca.png">

**Comment by jamorrison** [comment]
With the release of BISCUIT v1.2.0, the epiBED file format (default output for `biscuit epiread`) is now in alignment with the output from `biscuit pileup` (see the [version release notes](https://github.com/huishenlab/biscuit/releases/tag/v1.2.0.20230130) for caveats). It's suggested to switch over to this format from the old epiread format, which isn't guaranteed to match up with the results of `pileup`.
