### ISSUE TITLE
Wrong accounting of methylation calls in estimated overlaps

### ISSUE THREAD

**Issue by vpbrendel** [huishenlab/biscuit#25]
The pileup.c source code line 983 onward has the following comment:
"              /* If read 2 in a proper pair, skip counting overlapped cytosines
               * Right now I assume read 1 and read 2 are the same length and there is no gap.
               * Better solution would be to log mate end in the alignment (using bam_endpos).
               * The filtering of double counting is only effective when reads are properly paired.
               *  
               * The filtering removes bases from read 2 (usually the read on the complement strand)
               * that fall into the overlapped region.
               */
"
The term "better solution" is a gentle nudge in the right direction. In data sets I have analyzed, paired reads often overlap and rarely are of the same length (any quality control will likely create differences). In consequence, the pileup accounting gets very confusing and diverges quite a bit from other programs (bismark) which implement the filtering correctly (read 1 calls plus calls from the non-overlapping regions of read 2).

It's probably any easy fix for you with familiarity of the variable names, so I hope you'll be willing to fix this. As per your comment, all that is required is to determine the boundary of overlap correctly based on the actual read length.

Thanks, Volker

**Comment by jamorrison** [comment]
Thanks @vpbrendel for the push to make this fix. This has been addressed in both `pileup` and `epiread`. The commit message contains a brief description of what changes were made in doing this.
