### ISSUE TITLE
bug in statistical reporting

### ISSUE THREAD

**Issue by vpbrendel** [huishenlab/biscuit#26]
Line 81 of asm_pairwise.c:

If the intent is to show the Chi-square approximation to Fisher's Exact Test, then you need to specify the degrees of freedom to be 1 (not 2, as in the code).

I cannot think of a reason why df=2 should be used.

Volker

**Comment by jamorrison** [comment]
Thanks @vpbrendel for catching this. It's been changed in the code to df=1.
