### ISSUE TITLE
STRAND information in vcf2bed

### ISSUE THREAD

**Issue by nash5202** [huishenlab/biscuit#36]
Hello, 

Is there a way in `vcf2bed` to get strand information in the generated bed file from the `vcf` file? The output produced by `vcf2bed` does not have the strand information which is useful in case we want to check if promoter region of a gene is differentially methylated or not. For instance for TP53BP1, the promoter regions are located on the - strand. 

Any help is highly appreciated.

Thank you.

**Comment by jamorrison** [comment]
Hi @nash5202,

Except for the rare occurrences of hemi-methylation, DNA methylation is symmetric across the two strands (i.e., the same methylation state) due to the palindromic nature of the CG. Because of this, you don't have to separate the methylation across each strand.

Cheers,
Jacob
