### ISSUE TITLE
Issues with samblaster when using BISCUIT

### ISSUE THREAD

**Issue by KChadwick78** [huishenlab/biscuit#38]
Hi,
I am working on Compute Canada clusters and  getting an output error relating to samblaster when trying to align to me reference genome:

samblaster: Inputting from stdin
samblaster: Outputting to stdout
[M::bwa_idx_load_from_disk] read 0 ALT contigs
[gzread] (null)
samblaster: Loaded 172124 header sequence entries.
samblaster: No reads in input SAM file

**This is my code:**
module load gcc
module load bowtie2/2.4.1
module load samtools/1.16.1
module load samblaster/0.1.26
module load perl/5.30.2

biscuit align /home/chadders/projects/def-frasiert/methyl_seq/ref_genome/Eubalaena_glacialis_HiC.fasta 1151_B_S11_L001-FP.fastq  1151_B_S11_L001-RP.fastq |\
        samblaster | samtools sort -o my_output.bam -O BAM -

samtools index my_output.bam

I am super new to this and not sure if I have made a misstep in creating the reference index, but the outputs for this all looked ok. I know the fastq files are ok as they ran fine in bismark.

Thanks

**Comment by jamorrison** [comment]
Hi @KChadwick78,

Based on a little bit of testing on my end, it looks like the FASTQs you used as input weren't in the working directory you ran `biscuit` from.

I think it's fair to say that `[gzread] (null)` is not a helpful error message at all for this, so I will fix this to make it more obvious what is going on.

Feel free to reach out if you have further hang ups with running BISCUIT.

**Comment by KChadwick78** [comment]
Hi Jacob,

I went back to look closely at my directory after you mentioning this might
be the problem, as I was 99% I was running it from where my files are and
realised that I had missed off the '.gz' at the end which is why BISCUIT
couldn't find them as files with just the '.fastq' don't exist!
Getting to grips with this I can't see the wood for the trees sometimes :)
Thanks for your help

Kate
