### ISSUE TITLE
Extract SNPs in VCF format

### ISSUE THREAD

**Issue by bounlu** [huishenlab/biscuit#42]
Hi,

Is there a way to extract SNPs in VCF format rather than BED format from the pileup file?

`vcf2bed` -> `vcf2vcf`

**Comment by jamorrison** [comment]
Hi @bounlu,

There is not a utility in BISCUIT at this time to do that. However, if you have AWK, you could try something like

```
zcat ${FILE} |
awk '{
    if(substr($1,1,1) == "#") {
        print
    }
    if(substr($1,1,1) != "#" && $5 != ".") {
        print
    }
}' -
```

Or, if you wanted to additionally remove SNPs with the LowQual filter: 
```
zcat ${FILE} |
awk '{
    if(substr($1,1,1) == "#") {
        print
    }
    if(substr($1,1,1) != "#" && $5 != "." && $7 != "LowQual") {
        print
    }
}' -
```

**Comment by bounlu** [comment]
Thanks for the solution. So it's basically the 5. column in the original VCF to determine the type as methylation or SNP?

**Comment by jamorrison** [comment]
That's correct. Methylation-only entries will have a `.` in the fifth column, while entries with a SNP (which may also contain methylation values such as `BT`) will have a nucleotide (A/C/G/T/N) in the fifth column.

`${FILE}` represents the compressed (either gzip or bgzip) VCF. I've edited the comment to make this hopefully a little more clear.
