### ISSUE TITLE
SNP calling from Nanopore sequencing of bisulfite treated DNA

### ISSUE THREAD

**Issue by weishwu** [huishenlab/biscuit#47]
Can I use biscuit to do SNP calling with Nanopore sequencing reads from converted DNA? The reads will be aligned using Bismark with the `--mm2_nanopore` parameter.

**Comment by jamorrison** [comment]
Since your DNA has been cytosine converted, you should be able to do SNP calling with BISCUIT, even with using Bismark to do the alignments.

A (very) basic pipeline to do this is:
```
biscuit pileup -@ N_THREADS my_reference.fa nanopore.bismark.bam | bgzip -@ 3 - > my_pileup.vcf.gz
tabix -p vcf my_pileup.vcf.gz
biscuit vcf2bed -t snp my_pileup.vcf.gz
```
(See `biscuit pileup -h` and `biscuit vcf2bed -h` for additional options.)
