### ISSUE TITLE
[Issue] Issue with bgzipped bed file

### ISSUE THREAD

**Issue by njspix** [huishenlab/biscuit#49]
**Describe the bug**
`biscuit epiread` seems unable to parse a bgzipped SNP BED file.

**BISCUIT version**
```
biscuit --version

Program: BISCUIT (BISulfite-seq CUI Toolkit)
Version: 1.3.0
Contact: Jacob Morrison <jacob.morrison@vai.org>
```

**Minimally Reproducible Example**
```
biscuit vcf2bed -t snp -k 1 -s ALL EE17D4_pileup.vcf.gz | bgzip > EE17D4_snps.bed.gz
biscuit epiread -@ 60 -B EE17D4_snps.bed.gz -5 10 -3 1 -p mm10.fa EE17D4_bsconv_clean.bam | bgzip -@  2 > epiread.bed.gz
SNP BED (EE17D4_snps.bed.gz) is empty
```

This problem seems to have been introduced in 1.3.0, as 1.2.1 completes without issue.

**Comment by jamorrison** [comment]
This issue has been fixed and will appear in the next release of BISCUIT.
