### ISSUE TITLE
[Issue] "SNP BED (test_snp.bed.gz) is empty" when run biscuit epiread

### ISSUE THREAD

**Issue by fei0810** [huishenlab/biscuit#51]
**Describe the bug**
When running 
```
biscuit epiread -@ 10 -B CQ001TT_test_snp.bed b37_decoy+lambda+pUC19.fa CQ001TT-test.bam | sort -k1,1 -k2,2n | bgzip > CQ001TT_test_epiread.gz 
```
on WGBS data , I get the following error in stderr:

**SNP BED (CQ001TT_test_snp.bed) is empty**

But the snp file is get by `biscuit vcf2bed -t snp CQ001TT_test.vcf.gz > CQ001TT_test_snp.bed` and the results of the first ten rows are as follows. Obviously, this is not an empty file, and no other error messages occurred during running the previous commands. Therefore, this "empty" error message confused me a little.

```
1	186700996	186700997	A	C	0/1	A2C1	3	0.33
11	21270348	21270349	A	G	0/1	A1G2	3	0.67
11	21270351	21270352	A	T	0/1	A1T2	3	0.67
16	46386269	46386270	C	T	0/1	C2T1Y1	3	0.33
16	46391263	46391264	C	T	0/1	C3T1	4	0.25
16	46391310	46391311	T	G	0/1	T5G1Y1	7	0.14
16	46391354	46391355	T	C	0/1	T5C1Y2	6	0.17
16	46391410	46391411	T	C	0/1	T3C1Y2	4	0.25
16	46391462	46391463	A	N	0/1	Y1R2	3	0.33
16	46391485	46391486	A	C	0/1	A1C1R2	4	0.25

```

I want to know where the problem may be and how I should try to solve it. Thank you very much!

**BISCUIT version**
Version: 1.4.0

**Computer Resources**
 - OS: linux

**Comment by jamorrison** [comment]
Hi @fei0810,

This issue appears to be a similar problem to Issue #49. It has been resolved (79e72f5) and will be available in the next release (version 1.5.0), but I'm working to wrap up a new feature before that release is created. In the meantime, the fix is available on the master branch.

Best,
Jacob
