### ISSUE TITLE
[Question] Is it possible to set different trimming parameters for read 1 and read 2?

### ISSUE THREAD

**Issue by JiantaoShi** [huishenlab/biscuit#55]
**Describe the question**
In biscuit align, -5 and -3 could be used to set trimming parameters for 5' and 3'. But is it possible to set different values for read 1 and read 3?

**Comment by jamorrison** [comment]
Hi @JiantaoShi,

It is currently not possible to set different values for the two reads in paired-end sequencing. If your use case requires different values be trimmed, I would suggest using Cutadapt for trimming prior to alignment with BISCUIT.

Best,
Jacob
