### ISSUE TITLE
Deal with UMIs

### ISSUE THREAD

**Issue by seynard** [huishenlab/biscuit#57]
Hi, 

I have RRBS data with UMIs and I wanted to treat (group) them when running my analysis. 
Is there any parameters to do that within BISCUIT or should I deal for it prior to running the pipeline (often UMIs grouping is performed after mapping, on the bam file, I'm trying to find alternatives that would work on the fastq instead). 

Cheers,

**Comment by jamorrison** [comment]
HI @seynard,

I'm not sure of a way to do grouping on FASTQs, but you can process data with UMIs through BISCUIT. Note, the following steps assume your UMI is only on one read (read 1 is used as an example, but read 2 would behave similarly).

1. (If your reads have cell barcodes, you can skip this step.) Run your FASTQ with the UMI through [synthbar](https://github.com/jamorrison/synthbar). This adds a synthetic cell barcode to the start of the read for downstream compatibility purposes.
```
synthbar read1.fq.gz | gzip > read1.cb.fq.gz
```

2. Extract barcode and UMI with [umi-tools](https://github.com/CGATOxford/UMI-tools). The following code chunk has a cell barcode length of 7 (CCCCCCC) to match the output from `synthbar` and a UMI length of 6 (NNNNNN) which would need to be changed if your data has a different UMI length.
```
umi_tools extract \
    --extract-method=string \
    --bc-pattern=CCCCCCCNNNNNN \
    --stdin read1.cb.fq.gz \
    --stdout read1.umi_extracted.fq.gz \
    --read2-in=read2.fq.gz \
    --read2-out=read2.umi_extracted.fq.gz \
    -L extract.log
```

3. Align with BISCUIT
```
biscuit align \
    -9 -@ <NTHREADS> \
    /path/to/reference.fa \
    read1.umi_extracted.fq.gz \
    read2.umi_extracted.fq.gz | \
samtools view -o my_data.bam -
```

4. Group UMIs with `umi-tools`
```
umi_tools group \
    --stdin my_data.bam \
    --output-bam \
    --stdout my_data.sorted.grouped.bam \
    --group-out=grouped.tsv \
    --log=group.log \
    --paired \
    --extract-umi-method=tag \
    --umi-tag=RX \
    --cell-tag=CB
```

Depending on your use case, you may have to adjust or add options, but this should get you started in processing reads with UMIs through BISCUIT. Let me know if you have additional questions!

Best,
Jacob

**Comment by seynard** [comment]
Thanks so much for your help. 
Right after I sent this issue I worked out that I could totally integrate umi_tools to my analysis without bothering you with it. 
I'm really sorry about that. 
Thanks again a lot for your help. 
Best, Sonia

**Comment by jamorrison** [comment]
Not a problem. It provides other users something to reference for their own analyses if needed. Best of luck on your work!
