### ISSUE TITLE
[Issue] vcf2bed reported [Warning] Invalid number of fields in FMT, Skip line.

### ISSUE THREAD

**Issue by alexyfyf** [huishenlab/biscuit#6]
Please fill in as much as possible. The more information provided, the more likely we are to be able to help.

**Describe the bug**
I followed the manual to call SNPs from single end bisulphite sequencing data (ERRBS), with little modifications including accommodating single-end reads in samblaster using `--ignoreUnmated`, consider duplicated reads and minimum 0bp distance to read end (pileup -u -e 0).
However, when I run vcf2bed with the vcf.gz, it gave an error indicating the malformed VCF file. And the final bed file is empty, but looks like bam and vcf file is generated with information.

**BISCUIT version**
Version: 0.3.8.20180515

**Minimally Reproducible Example**
1. Reference genome: Ensembl [GRCm38](ftp://ftp.ensembl.org/pub/release-101/fasta/mus_musculus/dna/Mus_musculus.GRCm38.dna.primary_assembly.fa.gz)
2. Small dataset to run on [(fastq)](https://drive.google.com/drive/folders/1RfpWqNc3FCpCMsz3-Ngkm9sDg2FeSsrt?usp=sharing)
2. Command(s) 
```
FILE=test.fastq
BASE=test
REF=../index/Mus_musculus.GRCm38.dna.primary_assembly.fa
## index
biscuit index index/*.fa
## align
biscuit align -t 10 -M -R "@RG\tID:1\tSM:'$BASE'" $REF $FILE | \
        ~/ls25_scratch/feng.yan/software/samblaster/samblaster -M --ignoreUnmated | \
        samtools sort -@ 10 -o ${BASE}_mdups_sorted.bam -O BAM -
samtools index ${BASE}_mdups_sorted.bam
## snp call
## keep dup
biscuit pileup -o ${BASE}.vcf $REF ${BASE}_mdups_sorted.bam -q 12 \
        -v 1 \
        -u -e 0
bgzip ${BASE}.vcf
tabix -p vcf ${BASE}.vcf.gz
## extract
biscuit vcf2bed -t snp -k 1 -e ${BASE}.vcf.gz > ${BASE}_snp.bed
```
3. Error given
In vcf2bed it produced error message:
```
[Warning] Invalid number of fields in FMT, Skip line.
```

**Expected behavior**
A bed file or vcf file indicating genotype and SNP information.

**Computer Resources**
 - OS: Ubuntu
 - RAM: 64G
 - CPUs: 16

**Additional context**

**Screenshots**

**Comment by jamorrison** [comment]
Hi @alexyfyf,

Thanks for the detailed issue report. I noticed you are using BISCUIT version 0.3.8.20180515. Can you test if you get the same issue on the most recent release of BISCUIT ([v0.3.16.20200420](https://github.com/huishenlab/biscuit/releases/tag/v0.3.16.20200420))?

Thanks,
Jacob

**Comment by alexyfyf** [comment]
Yes, I have run it with 0.3.16 again. And there's exactly the same error.
```
## align
/home/fyan0011/ls25_scratch/feng.yan/software/biscuit_0_3_16_linux_amd64 align -t 10 -M -R "@RG\tID:1\tSM:'$BASE'" $REF $FILE | \
        ~/ls25_scratch/feng.yan/software/samblaster/samblaster -M --ignoreUnmated | \
        samtools sort -@ 10 -o ${BASE}_mdups_sorted.bam -O BAM -

samtools index ${BASE}_mdups_sorted.bam

## snp call
## keep dup

/home/fyan0011/ls25_scratch/feng.yan/software/biscuit_0_3_16_linux_amd64 pileup -o ${BASE}.vcf $REF ${BASE}_mdups_sorted.bam -q 12 \
        -v 1 \
        -u -e 0

bgzip ${BASE}.vcf
tabix -p vcf ${BASE}.vcf.gz

/home/fyan0011/ls25_scratch/feng.yan/software/biscuit_0_3_16_linux_amd64 vcf2bed -t snp -k 10 -e ${BASE}.vcf.gz > ${BASE}_snp.bed
#biscuit vcf2bed -t cg -k 10 -e ${BASE}.vcf.gz > ${BASE}_c.bed
```

Two repeated errors, just as example, and almost all lines are skipped due to the warning invalid number of filed in FMT
```
[Warning] Invalid number of fields in FMT, Skip line.
Malformed VCF file (unmatched no. records) in 1	3045574	.	T	C	5	LowQual	NS=1	GT:GL1:GQ:DP:SP:AC:AF1	1/1:-6,-2,-1:5:1:C1:1:1.00	DIAGNOSE;RN=0;CN=0;Bs1=C;Sta1=2;Bq1=A;Str1=-;Pos1=46;Rret1=10
```

Also here's the generated pileup files, only showing first few lines
```
1	3005823	.	C	.	5	LowQual	NS=1;CX=CHH;N5=AGCTT	GT:GL1:GQ:DP:SP	0/0:-1,-2,-6:5:1:C1	DIAGNOSE;RN=0;CN=0;Bs1=C;Sta1=2;Bq1=@;Str1=-;Pos1=1;Rret1=16
1	3005824	.	T	.	5	LowQual	NS=1	GT:GL1:GQ:DP:SP	0/0:-1,-2,-6:5:1:T1	DIAGNOSE;RN=0;CN=0;Bs1=T;Sta1=2;Bq1=@;Str1=-;Pos1=2;Rret1=16
1	3005825	.	T	.	5	LowQual	NS=1	GT:GL1:GQ:DP:SP	0/0:-1,-2,-6:5:1:T1	DIAGNOSE;RN=0;CN=0;Bs1=T;Sta1=2;Bq1=?;Str1=-;Pos1=3;Rret1=16
```
Not sure where is the FMT issue.
Thank you!

**Comment by jamorrison** [comment]
Thanks for testing the new version. I'll look into the issue.

**Comment by jamorrison** [comment]
Hi @alexyfyf,

I did some looking into your issue. When running `biscuit pileup`, you've included `-v 1`, which is used for diagnostic purposes and does not create a standards compliant VCF file. Running `biscuit vcf2bed` on a VCF file generated with `-v 1` included will return the WARNING message you received.

If you remove `-v 1` from your `biscuit pileup` command, you will get a properly formatted BED file with `vcf2bed` (verified with provided test data).

Cheers,
Jacob

**Comment by alexyfyf** [comment]
Thank you for make it clear!
