### ISSUE TITLE
[Issue] asm results interpretation and how to deal with across different samples 

### ISSUE THREAD

**Issue by DerekTerry** [huishenlab/biscuit#9]
I have got ASM results for each sample, but I am confused about each column( and I have not yet find the publication). 

And Is there any  strategy in dealing with multiply asm results, such as intersect only  the same block among samples 

**ASM results**

sample 01
```
CM022019.1      100000174       100000108       A/G     T/C     5       3       0       2       0.444444        0.286505
CM022019.1      100000174       100000152       A/G     T/C     5       8       0       2       0.523810        0.561624
CM022019.1      100000389       100000495       T/C     T/C     4       1       0       1       0.333333        0.301194
CM022019.1      100000463       100000495       T/C     T/C     7       3       0       2       0.151515        0.186374
CM022019.1      100000496       100000494       A/G     T/C     2       0       0       1       0.333333        0.223130
CM022019.1      100000496       100000495       A/G     T/C     7       0       0       6       0.000583        0.001503
CM022019.1      100000721       100000706       A/G     T/C     1       15      0       2       1.000000        0.935966
CM022019.1      100000721       100000802       A/G     T/C     4       4       1       0       1.000000        0.637628
CM022019.1      100000755       100000706       T/C     T/C     1       11      0       1       1.000000        0.955865
CM022019.1      100000755       100000802       T/C     T/C     4       6       1       3       1.000000        0.869358
CM022019.1      10000137        10000038        A/G     T/C     2       3       1       0       1.000000        0.548812
CM022019.1      100001901       100001821       A/T     T/C     0       11      1       0       0.083333        0.002479
CM022019.1      100001948       100001947       T/C     T/C     9       0       0       2       0.018182        0.004087
CM022019.1      100002047       100002046       T/C     T/C     9       0       0       4       0.001399        0.001503
```

sample 02
```
CM022019.1      100000496       100000494       A/G     T/C     3       0       1       3       0.142857        0.139631
CM022019.1      100000496       100000495       A/G     T/C     12      0       0       6       0.000054        0.000123
CM022019.1      100000755       100000706       T/C     T/C     2       4       0       2       1.000000        0.641180
CM022019.1      100000755       100000802       T/C     T/C     1       1       1       1       1.000000        1.000000
CM022019.1      10000101        10000039        T/C     T/C     0       1       2       1       1.000000        0.513417
CM022019.1      100001901       100001821       A/T     T/C     1       9       0       2       1.000000        0.896649
CM022019.1      100001901       100001947       A/T     T/C     6       5       0       2       0.461538        0.363133
CM022019.1      100001948       100001822       T/C     T/C     0       1       2       0       0.333333        0.223130
CM022019.1      100001948       100001947       T/C     T/C     8       0       0       9       0.000041        0.000203
CM022019.1      100001948       100002046       T/C     T/C     2       1       2       0       1.000000        0.659241
CM022019.1      100002047       100001947       T/C     T/C     2       2       1       0       1.000000        0.659241
CM022019.1      100002047       100002046       T/C     T/C     8       0       0       3       0.006061        0.004087

```

**BISCUIT version**
Program: BISCUIT (BISulfite-seq CUI Toolkit)
Version: 0.3.16.20200420

**Comment by jamorrison** [comment]
Hi @DerekTerry,

Apologies for the delayed response. The columns for the `asm` output are as follows:

  1. Chromosome name
  2. SNP location
  3. CpG location
  4. SNP_1/SNP_2 (SNPs for row_1/row_2 in contingency table)
  5. CpG_1/CpG_2 (CpGs for col_1/col_2 in contingency table)
  6. SNP_1-CpG_1 count (contingency table value in row_1-col_1)
  7. SNP_1-CpG_2 count (contingency table value in row_1-col_2)
  8. SNP_2-CpG_1 count (contingency table value in row_2-col_1)
  9. SNP_2-CpG_2 count (contingency table value in row_2-col_2)
  10. Two-tail Fisher's exact p-value
  11. &chi;<sup>2</sup> p-value

The publication is still in progress, but documentation for BISCUIT can be found at: https://huishenlab.github.io/biscuit/.

As for multiple `asm` samples, there is no current best practices for how to intersect blocks across samples.

**Comment by DerekTerry** [comment]
Many Thx! ——————————————UTao  CaoCAST, China Agricultural University.a: 2 Yuanmingyuan West Rd., Haidian District | Beijing ,PRC,100193 e: utao.cho.cau@outlook.com-------- 原始邮件 --------发件人： Jacob Morrison <notifications@github.com>日期： 2021年1月12日周二 半夜12:01收件人： huishenlab/biscuit <biscuit@noreply.github.com>抄送： Durian <dedicatedforsss@163.com>, Mention <mention@noreply.github.com>主    题： Re: [huishenlab/biscuit] [Issue] asm results interpretation and how to deal with across different samples  (#9)

Hi @DerekTerry,

Apologies for the delayed response. The columns for the asm output are as follows:

Chromosome nameSNP locationCpG locationSNP_1/SNP_2 (SNPs for row_1/row_2 in contingency table)CpG_1/CpG_2 (CpGs for col_1/col_2 in contingency table)SNP_1-CpG_1 count (contingency table value in row_1-col_1)SNP_1-CpG_2 count (contingency table value in row_1-col_2)SNP_2-CpG_1 count (contingency table value in row_2-col_1)SNP_2-CpG_2 count (contingency table value in row_2-col_2)Two-tail Fisher's exact p-valueχ2 p-value

The publication is still in progress, but documentation for BISCUIT can be found at: https://huishenlab.github.io/biscuit/.

As for multiple asm samples, there is no current best practices for how to intersect blocks across samples.
